# Numpy

In [41]:
import numpy as np

In [42]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr = np.array(l)

In [43]:
type(arr)

numpy.ndarray

In [44]:
np.asarray(l)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
np.asanyarray(l)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
b = np.matrix(l)

In [47]:
b

matrix([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [48]:
np.asanyarray(b)

matrix([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [49]:
a = np.array(l)

In [50]:
c=a

In [51]:
a[0]=200

In [52]:
a

array([200,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [53]:
c

array([200,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [54]:
c[0]=100

In [55]:
c

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [56]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [57]:
d = np.copy(a)

In [58]:
d

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [59]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [60]:
a[1]=300

In [61]:
a

array([100, 300,   3,   4,   5,   6,   7,   8,   9,  10])

In [62]:
d

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [63]:
np.fromfunction(lambda i,j:i==j, (3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [64]:
np.fromfunction(lambda i,j:i*j, (3, 3))


array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [65]:
iterable = (i*i for i in range(5))

In [66]:
np.fromiter(iterable,float)


array([ 0.,  1.,  4.,  9., 16.])

In [67]:
np.fromstring('1 2 3 4 5', dtype=float, sep=' ')

array([1., 2., 3., 4., 5.])

In [68]:
np.fromstring('4,5', sep=',')

array([4., 5.])

In [69]:
np.fromstring("4'5", sep="'")

array([4., 5.])

In [70]:
np.fromstring('4"5', sep='"')

array([4., 5.])

In [71]:
arr.ndim

1

In [72]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2.ndim

2

In [73]:
arr2.size

6

In [74]:
arr2.shape

(2, 3)

In [75]:
arr2.dtype

dtype('int32')

In [76]:
arr3 = np.array([(1, 2.2, 3), (4, 5, 6)])

In [77]:
arr3.dtype

dtype('float64')

In [78]:
range(5)

range(0, 5)

In [79]:
list(range(5))  # Range takes integer always not float

[0, 1, 2, 3, 4]

In [80]:
# list(range(0.1,5))

In [81]:
np.arange(0.2,5)

array([0.2, 1.2, 2.2, 3.2, 4.2])

In [82]:
list(np.arange(2.2,6,0.3))

[2.2,
 2.5,
 2.8,
 3.0999999999999996,
 3.3999999999999995,
 3.6999999999999993,
 3.999999999999999,
 4.299999999999999,
 4.599999999999999,
 4.899999999999999,
 5.199999999999998,
 5.499999999999998,
 5.799999999999998]

In [83]:
np.linspace(0, 10, 5)  # Start, Stop, Number of points

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [84]:
np.zeros((2, 3))  # Shape of the array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [85]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [86]:
arr4 = np.zeros((3,4,2,5))

In [87]:
arr4.ndim

4

In [88]:
np.ones(4)

array([1., 1., 1., 1.])

In [89]:
on = np.ones((2, 3))  # Shape of the array

In [90]:
on

array([[1., 1., 1.],
       [1., 1., 1.]])

In [91]:
on + 5

array([[6., 6., 6.],
       [6., 6., 6.]])

In [93]:
on * 4  

array([[4., 4., 4.],
       [4., 4., 4.]])

In [96]:
np.empty((2, 6))  # Shape of the array

array([[1.01809512e-311, 1.01809512e-311, 1.01809512e-311,
        1.24610723e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.29061142e-306,
        7.56606597e-307, 6.23057349e-307, 1.20160711e-306]])

In [97]:
np.eye(3)  # Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [99]:
np.linspace(0, 10, 50)  # Start, Stop, Number of points

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [100]:
np.logspace(0, 10, 50)  # Start, Stop, Number of points

array([1.00000000e+00, 1.59985872e+00, 2.55954792e+00, 4.09491506e+00,
       6.55128557e+00, 1.04811313e+01, 1.67683294e+01, 2.68269580e+01,
       4.29193426e+01, 6.86648845e+01, 1.09854114e+02, 1.75751062e+02,
       2.81176870e+02, 4.49843267e+02, 7.19685673e+02, 1.15139540e+03,
       1.84206997e+03, 2.94705170e+03, 4.71486636e+03, 7.54312006e+03,
       1.20679264e+04, 1.93069773e+04, 3.08884360e+04, 4.94171336e+04,
       7.90604321e+04, 1.26485522e+05, 2.02358965e+05, 3.23745754e+05,
       5.17947468e+05, 8.28642773e+05, 1.32571137e+06, 2.12095089e+06,
       3.39322177e+06, 5.42867544e+06, 8.68511374e+06, 1.38949549e+07,
       2.22299648e+07, 3.55648031e+07, 5.68986603e+07, 9.10298178e+07,
       1.45634848e+08, 2.32995181e+08, 3.72759372e+08, 5.96362332e+08,
       9.54095476e+08, 1.52641797e+09, 2.44205309e+09, 3.90693994e+09,
       6.25055193e+09, 1.00000000e+10])

In [101]:
np.logspace(0, 10, 50,base=2)  # Start, Stop, Number of points

array([1.00000000e+00, 1.15195282e+00, 1.32699530e+00, 1.52863599e+00,
       1.76091654e+00, 2.02849277e+00, 2.33672798e+00, 2.69180039e+00,
       3.10082705e+00, 3.57200647e+00, 4.11478293e+00, 4.74003581e+00,
       5.46029763e+00, 6.29000526e+00, 7.24578931e+00, 8.34680745e+00,
       9.61512839e+00, 1.10761743e+01, 1.27592302e+01, 1.46980313e+01,
       1.69314386e+01, 1.95042185e+01, 2.24679395e+01, 2.58820063e+01,
       2.98148502e+01, 3.43453008e+01, 3.95641662e+01, 4.55760529e+01,
       5.25014628e+01, 6.04792082e+01, 6.96691946e+01, 8.02556253e+01,
       9.24506940e+01, 1.06498838e+02, 1.22681637e+02, 1.41323458e+02,
       1.62797956e+02, 1.87535565e+02, 2.16032123e+02, 2.48858814e+02,
       2.86673613e+02, 3.30234477e+02, 3.80414538e+02, 4.38219601e+02,
       5.04808306e+02, 5.81515352e+02, 6.69878251e+02, 7.71668141e+02,
       8.88925293e+02, 1.02400000e+03])

In [104]:
ar = np.random.rand(2, 3)  # Random numbers in the range [0, 1)

In [105]:
ar

array([[0.53262563, 0.40238672, 0.99612632],
       [0.19402684, 0.37404665, 0.23423516]])

In [103]:
import pandas as pd

In [106]:
pd.DataFrame(ar)

0         1         2
0  0.532626  0.402387  0.996126
1  0.194027  0.374047  0.234235

In [107]:
np.random.randn(2, 3)  # Random numbers from a standard normal distribution (mean=0, std=1)

array([[-0.39990577,  1.89112266,  0.7329272 ],
       [ 1.1596504 ,  2.34520402,  0.93708294]])

In [108]:
np.random.randint(0,10,(2,3))  # Random integers from 0 to 10, shape (2, 3)

array([[6, 2, 4],
       [0, 4, 9]])

In [111]:
pd.DataFrame(np.random.randint(1,100,(20,30))).to_csv("test.csv")  # Random integers from 1 to 100, shape (2, 3)

In [120]:
arr1 = np.random.rand(6, 3)  # Random numbers in the range [0, 1)

In [121]:
arr1

array([[0.91643403, 0.54453188, 0.20292142],
       [0.94937371, 0.53148684, 0.20581823],
       [0.26245404, 0.25940473, 0.30642839],
       [0.27697736, 0.65410091, 0.20370842],
       [0.37885835, 0.96627726, 0.54794148],
       [0.62101766, 0.84654792, 0.01991778]])

In [126]:
arr2 = arr1.reshape(9, 2)  # Reshape the array to shape (3, 2)

In [127]:
arr2

array([[0.91643403, 0.54453188],
       [0.20292142, 0.94937371],
       [0.53148684, 0.20581823],
       [0.26245404, 0.25940473],
       [0.30642839, 0.27697736],
       [0.65410091, 0.20370842],
       [0.37885835, 0.96627726],
       [0.54794148, 0.62101766],
       [0.84654792, 0.01991778]])

In [129]:
arr1[0][2]

0.202921421546562

In [134]:
arr2[3:6,1]

array([0.25940473, 0.27697736, 0.20370842])

In [140]:
arr2[3:6][0:2,1][0]

0.2594047333160896

In [142]:
arr = np.random.randint(1,100,(5,5))  # Random integers from 1 to 100, shape (5, 5)

In [143]:
arr

array([[68, 85, 80, 22, 14],
       [59, 34, 26, 16, 78],
       [69, 47, 48, 42, 90],
       [10, 43, 79, 49, 58],
       [ 9, 56, 29,  2,  2]])

In [145]:
arr[arr>50]

array([68, 85, 80, 59, 78, 69, 90, 79, 58, 56])

In [146]:
arr[2:4,1:3]

array([[47, 48],
       [43, 79]])

In [147]:
arr[2:4,[1,2]]

array([[47, 48],
       [43, 79]])

In [149]:
arr[0][0]=200

In [150]:
arr

array([[200,  85,  80,  22,  14],
       [ 59,  34,  26,  16,  78],
       [ 69,  47,  48,  42,  90],
       [ 10,  43,  79,  49,  58],
       [  9,  56,  29,   2,   2]])

In [151]:
ar1 = np.random.randint(1,100,(5,5))  # Random integers from 1 to 100, shape (5, 5)

ar2 = np.random.randint(1,100,(5,5))  # Random integers from 1 to 100, shape (5, 5)

In [152]:
ar1

array([[49, 46, 29, 64, 40],
       [70, 60, 53, 44, 90],
       [73, 73, 34, 56, 31],
       [55, 66, 98, 58, 78],
       [18, 67, 56, 29, 85]])

In [153]:
ar2

array([[67, 28, 53, 40, 49],
       [ 4, 72, 99, 16, 47],
       [40, 28, 87, 39, 62],
       [16, 15, 83, 76, 83],
       [28, 53,  2, 64, 62]])

In [155]:
ar1 + ar2 # Element-wise addition

array([[116,  74,  82, 104,  89],
       [ 74, 132, 152,  60, 137],
       [113, 101, 121,  95,  93],
       [ 71,  81, 181, 134, 161],
       [ 46, 120,  58,  93, 147]])

In [156]:
ar1 - ar2 # Element-wise subtraction

array([[-18,  18, -24,  24,  -9],
       [ 66, -12, -46,  28,  43],
       [ 33,  45, -53,  17, -31],
       [ 39,  51,  15, -18,  -5],
       [-10,  14,  54, -35,  23]])

In [157]:
ar1/ ar2 # Element-wise division

array([[ 0.73134328,  1.64285714,  0.54716981,  1.6       ,  0.81632653],
       [17.5       ,  0.83333333,  0.53535354,  2.75      ,  1.91489362],
       [ 1.825     ,  2.60714286,  0.3908046 ,  1.43589744,  0.5       ],
       [ 3.4375    ,  4.4       ,  1.18072289,  0.76315789,  0.93975904],
       [ 0.64285714,  1.26415094, 28.        ,  0.453125  ,  1.37096774]])

In [158]:
ar1* ar2 # Element-wise multiplication

array([[3283, 1288, 1537, 2560, 1960],
       [ 280, 4320, 5247,  704, 4230],
       [2920, 2044, 2958, 2184, 1922],
       [ 880,  990, 8134, 4408, 6474],
       [ 504, 3551,  112, 1856, 5270]])

In [159]:
ar1 @ ar2  # Matrix multiplication

array([[ 6771,  8576, 15066, 11251, 14153],
       [10274, 13194, 18093, 14931, 18768],
       [ 8307, 10735, 18764, 11654, 15686],
       [10981, 14040, 22945, 16478, 21523],
       [ 6558, 11836, 15036, 11620, 15180]])

In [160]:
ar1/0

C:\Users\lalch\AppData\Local\Temp\ipykernel_380\3042774750.py:1: RuntimeWarning: divide by zero encountered in divide
  ar1/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [162]:
ar1

array([[49, 46, 29, 64, 40],
       [70, 60, 53, 44, 90],
       [73, 73, 34, 56, 31],
       [55, 66, 98, 58, 78],
       [18, 67, 56, 29, 85]])

In [161]:
ar1 + 100


array([[149, 146, 129, 164, 140],
       [170, 160, 153, 144, 190],
       [173, 173, 134, 156, 131],
       [155, 166, 198, 158, 178],
       [118, 167, 156, 129, 185]])

In [163]:
ar1**2

array([[2401, 2116,  841, 4096, 1600],
       [4900, 3600, 2809, 1936, 8100],
       [5329, 5329, 1156, 3136,  961],
       [3025, 4356, 9604, 3364, 6084],
       [ 324, 4489, 3136,  841, 7225]])

In [164]:
a = np.zeros((3, 3))  # Create a 3x3 array of zeros

In [165]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [166]:
row = np.array([1, 2, 3])  # Create a row vector

In [170]:
row

array([1, 2, 3])

In [167]:
a + row  # Broadcasting: adds the row vector to each row of the array

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [172]:
row.T # Transpose the row vector to a column vector only when >1D

array([1, 2, 3])

In [175]:
col = np.array([[1,2,3]])  # Create a column vector

In [176]:
col

array([[1, 2, 3]])

In [178]:
a + col.T  # Broadcasting: adds the column vector to each column of the array

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [182]:
np.sqrt(ar)     # Element-wise square root

array([[0.72981205, 0.63433959, 0.99806128],
       [0.44048478, 0.61159353, 0.48397848]])

In [181]:
np.exp(ar)  # Element-wise exponential

array([[1.70339893, 1.49538951, 2.70777244],
       [1.21412887, 1.45360495, 1.26394169]])

In [183]:
np.log10(ar)  # Element-wise logarithm base 10

array([[-0.27357794, -0.39535636, -0.00168558],
       [-0.71213819, -0.42707424, -0.63034791]])